CREATE TABLE IF NOT EXISTS local_message_record (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoke_json CLOB NOT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  next_retry_time TIMESTAMP NOT NULL,
  retry_times INT NOT NULL DEFAULT 0,
  max_retry_times INT NOT NULL DEFAULT 3,
  fail_reason VARCHAR(2000),
  create_time TIMESTAMP NOT NULL,
  update_time TIMESTAMP NOT NULL
);
